// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMv_x4y-6FBmDUGWWO55Duw3NiXJJV0So',
    appId: '1:388535345552:web:03881aa1f3aa145bd61315',
    messagingSenderId: '388535345552',
    projectId: 'trabalho-final-pgdb',
    authDomain: 'trabalho-final-pgdb.firebaseapp.com',
    storageBucket: 'trabalho-final-pgdb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9sx58QNXQZb_ochZB_HWBC-HOe75WqJ0',
    appId: '1:388535345552:android:b2c215b19ebf583fd61315',
    messagingSenderId: '388535345552',
    projectId: 'trabalho-final-pgdb',
    storageBucket: 'trabalho-final-pgdb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOp1SBtmfysxyw1AgU8pAO8v9hauAWA8c',
    appId: '1:388535345552:ios:5341881c094343f9d61315',
    messagingSenderId: '388535345552',
    projectId: 'trabalho-final-pgdb',
    storageBucket: 'trabalho-final-pgdb.appspot.com',
    iosBundleId: 'com.example.pgdbapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOp1SBtmfysxyw1AgU8pAO8v9hauAWA8c',
    appId: '1:388535345552:ios:98ad431a03015356d61315',
    messagingSenderId: '388535345552',
    projectId: 'trabalho-final-pgdb',
    storageBucket: 'trabalho-final-pgdb.appspot.com',
    iosBundleId: 'com.example.pgdbapp.RunnerTests',
  );
}
